site_name: Nimbus
repo_url: https://github.com/mdsreq-fga-unb/2024.1-Nimbus
repo_name: 2024.1-Nimbus

nav:
  - Home: index.md
  - História: faccao/faccao.md
  - Visão Geral do Produto e Projeto:
    - Visão Geral do Produto: visao-geral/visao-produto.md
    - Visão Geral do Projeto: visao-geral/visao-projeto.md
    - Processo de Desenvolvimento: visao-geral/processo-desenvolvimento.md
  - Missão 1:
    - Questionário: missoes/missao1/questionario.md
    - Lições aprendidas: missoes/missao1/licoes-aprendidas.md
    - Slides Fundamentos de ESW: missoes/missao1/fundamentos.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  font:
    text: Ubuntu

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - navigations.indexes
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight

  nav_style: dark
  language: pt
  repo: fontawesome/brands/github
  logo: img/brasao2.png
  favicon: img/brasao.ico

  palette:
    - scheme: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Alternar para modo escuro
      primary: grey
      accent: light blue

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Alternar para modo claro
      primary: black
      accent: light blue

  markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
      pygments_lang_class: true
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.inlinehilite
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.snippets

extra_css:
  - stylesheets/extra.css
